model_arch: RCGNN
depth: 4
pool: "add"
sub_aggr: "mean"
only_ground: True
residual: True
norm: "layer"
mask: True
trainer: supervised_qm9
learning_rate: 0.0002
RFF_dim: null
RFF_sigma: null
epochs: 30
warmup_epochs: 3
batch_size: 48
fully_connect: False
hidden_features: 64
edge_features: 3
no_relations: False
subgraph_dict: null
node_features: 9
LABEL_INDEX: 7
out_features: 1
data_dir: "./data/qm9"
model_dir: "./trained/qm9"
log_dir: "./logs"
optimizer:
  name: Adam
  kwargs:
    betas: [0.9, 0.999]
    eps: 1e-8
criterion:
  name: L1Loss
scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: ${epochs}
device: cuda
