model_arch: RelEGNN
depth: 5
pool: "add"
sub_aggr: "mean"
only_ground: False
residual: True
norm: "layer"
mask: False
trainer: supervised_qm9
learning_rate: 0.0005
RFF_dim: null
RFF_sigma: null
epochs: 800
warmup_epochs: 5
batch_size: 96
fully_connect: False
hidden_features: 128
num_relations: 3
subgraph_dict: null
node_features: 9
LABEL_INDEX: 7
out_features: 1
data_dir: "./data/qm9"
model_dir: "./trained/qm9"
log_dir: "./logs"
optimizer:
  name: Adam
  kwargs:
    betas: [0.9, 0.999]
    eps: 1e-8
criterion:
  name: L1Loss
scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: ${epochs}
device: cuda
