model_arch: Simple_Transformer_MPNN
depth: 2
pool: "none"
sub_aggr: "mean"
only_ground: True
residual: True
norm: "layer"
mask: False
trainer: wikics
learning_rate: 0.01
subgraph_dict:
  mode: "transformer_4"
dropout: 0.4
epochs: 100
transform: null
batch_size: 64
fully_connect: True
hidden_features: 48
edge_features: 0
node_features: 304
out_features: 10
data_dir: "./data/wikics"
model_dir: "./trained/wikics"
log_dir: "./logs"
device: cuda
