model_arch: Simple_MPNN
depth: 2
pool: "none"
sub_aggr: "mean"
only_ground: True
residual: True
norm: "layer"
mask: False
trainer: wikics
learning_rate: 0.02
subgraph_dict:
  mode: "transformer_8"
dropout: 0.5
epochs: 150
transform: null
batch_size: 64
fully_connect: True
hidden_features: 48
edge_features: 0
node_features: 308
out_features: 10
data_dir: "./data/wikics"
model_dir: "./trained/wikics"
log_dir: "./logs"
device: cuda
