model_arch: EGNN
depth: 2
pool: "add"
add_residual_skip: True
norm: "batch"
masking: False
trainer: md17_lightning
learning_rate: 0.0005
epochs: 30
batch_size: 32
subgraph_dict: null
fully_connect: True
node_features: 9
Z_ONE_HOT_DIM: 11
name: "aspirin CCSD"
EDGE_ATTR_DIM: 4
edge_features: 0
hidden_features: 64
out_features: 1
data_dir: "./data/md17"
model_dir: "./trained/md17"
log_dir: "./logs"
optimizer:
  name: Adam
  kwargs:
    betas: [0.9, 0.999]
    eps: 1e-8
criterion:
  name: L1Loss
scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: ${epochs}
device: cuda
