model_arch: Fractal_EGNN_v2
depth: 2
pool: "add"
only_ground: True
add_residual_skip: True
norm: "none"
mask: True
trainer: md17
learning_rate: 0.0004
RFF_dim: 96
RFF_sigma: 10
epochs: 800
batch_size: 4
subgraph_dict:
  mode: "fractal"
fully_connect: True
node_features: 9
Z_ONE_HOT_DIM: 11
name: "aspirin CCSD"
EDGE_ATTR_DIM: 4
edge_features: 0
hidden_features: 48
out_features: 1
data_dir: "./data/md17"
model_dir: "./trained/md17"
log_dir: "./logs"
optimizer:
  name: Adam
  kwargs:
    betas: [0.9, 0.999]
    eps: 1e-8
criterion:
  name: L1Loss
scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: ${epochs}
device: cuda
