model_arch: Fractal_EGNN
depth: 1
pool: "add"
add_residual_skip: True
norm: "layer"
masking: False
trainer: md17
learning_rate: 0.0004
RFF_dim: 64
RFF_sigma: 6.0
epochs: 700
batch_size: 4
subgraph_dict:
  mode: "fractal"
fully_connect: True
node_features: 9
Z_ONE_HOT_DIM: 11
name: "aspirin CCSD"
EDGE_ATTR_DIM: 4
edge_features: 0
hidden_features: 64
out_features: 1
data_dir: "./data/md17"
model_dir: "./trained/md17"
log_dir: "./logs"
optimizer:
  name: Adam
  kwargs:
    betas: [0.9, 0.999]
    eps: 1e-8
criterion:
  name: L1Loss
scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: ${epochs}
device: cuda
