model_arch: Transformer_EGNN_v2
depth: 4
ascend_depth: 4
num_heads: 2
num_ascend_heads: 2
pool: "add"
sub_aggr: "mean"
only_ground: True
residual: True
norm: "layer"
mask: True
trainer: md17
learning_rate: 0.0003
RFF_dim: 96
RFF_sigma: 10
epochs: 5
warmup_epochs: 1
batch_size: 4
subgraph_dict:
  mode: "transformer_10"
node_features: 19
fully_connect: True
name: "aspirin CCSD"
edge_features: 0
hidden_features: 48
out_features: 1
data_dir: "./data/md17"
model_dir: "./trained/md17"
log_dir: "./logs"
optimizer:
  name: Adam
  kwargs:
    betas: [0.9, 0.999]
    eps: 1e-8
criterion:
  name: L1Loss
scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: ${epochs}
device: cuda
