model_arch: Transformer_EGNN_v2
depth: 3
ascend_depth: 0
num_heads: 1
num_ascend_heads: 0
pool: "add"
sub_aggr: "add"
only_ground: False
only_sub: True
residual: True
norm: "layer"
mask: True
trainer: md17
learning_rate: 0.0002
RFF_dim: 96
RFF_sigma: 10
epochs: 1200
weight: 1000
warmup_epochs: 50
batch_size: 4
subgraph_dict:
  mode: "transformer_4"
node_features: 17
fully_connect: True
name: "benzene CCSD(T)"
edge_features: 0
hidden_features: 48
out_features: 1
data_dir: "./data/md17"
model_dir: "./trained/md17"
log_dir: "./logs"
optimizer:
  name: Adam
  kwargs:
    betas: [0.9, 0.999]
    eps: 1e-8
criterion:
  name: L1Loss
scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: ${epochs}
device: cuda
