model_arch: Fractal_EGNN_v2
depth: 2
ascend_depth: 0
num_heads: 1
num_ascend_heads: 0
pool: "add"
sub_aggr: "add"
only_ground: False
only_sub: False
residual: True
norm: "layer"
mask: True
trainer: mnist
learning_rate: 0.001
RFF_dim: 48
RFF_sigma: 6
epochs: 100
radius: 8
warmup_epochs: 2
batch_size: 16
fully_connect: True
subgraph_dict:
  mode: "fractal"
node_features: 1
LABEL_INDEX: 7
edge_features: 0
hidden_features: 48
out_features: 10
data_dir: "./data/mnist"
model_dir: "./trained/mnist"
log_dir: "./logs"
optimizer:
  name: Adam
  kwargs:
    betas: [0.9, 0.999]
    eps: 1e-8
criterion:
  name: L1Loss
scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: ${epochs}
device: cuda
