EDGE_ATTR_DIM: 4
LABEL_INDEX: 7
Z_ONE_HOT_DIM: 5
batch_size: 32
dataset: qm9
edge_features: 0
epochs: 1
hidden_features: 64
learning_rate: 0.0003
log_dir: ./logs
model_arch: fractalnet
model_dir: ./trained/qm9
model_name: fractalnet_495761
node_features: 5
out_features: 1
run_id: 495761
test_data: ./data/qm9
train_data: ./data/qm9
val_data: ./data/qm9
