EDGE_ATTR_DIM: 4
LABEL_INDEX: 7
Z_ONE_HOT_DIM: 5
batch_size: 32
criterion:
  name: MSELoss
dataset: qm9
device: cuda
edge_features: 0
epochs: 1
hidden_features: 64
learning_rate: 0.0003
log_dir: ./logs
model_arch: fractalnet
model_dir: ./trained/qm9
model_name: fractalnet_632151
node_features: 5
optimizer:
  kwargs:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
  name: Adam
out_features: 1
run_id: 632151
scheduler:
  kwargs:
    factor: 0.1
    mode: min
    patience: 5
    verbose: true
  name: ReduceLROnPlateau
test_data: ./data/qm9
train_data: ./data/qm9
val_data: ./data/qm9
