EDGE_ATTR_DIM: 4
LABEL_INDEX: 7
Z_ONE_HOT_DIM: 5
batch_size: 32
criterion:
  name: MSELoss
data_dir: ./data/qm9
dataset: qm9
device: cuda
edge_features: 0
epochs: 1
hidden_features: 64
learning_rate: 0.0003
log_dir: ./logs
model_arch: fractalnet
model_dir: ./trained/qm9
model_name: fractalnet_633318
node_features: 5
optimizer:
  name: Adam
  params:
    lr: 0.001
out_features: 1
run_id: 633318
scheduler:
  name: StepLR
  params:
    gamma: 0.1
    step_size: 10
seed: 42
subgraph: true
