model_arch: gnn_no_rel
num_convolution_blocks: 4
pooling: "mean"
add_residual_skip: True
layernorm: True
masking: False
trainer: qm9
learning_rate: 0.0003
epochs: 80
batch_size: 64
subgraph: False
n_node_features: 5
n_edge_features: 0
n_hidden: 64
n_output: 1
edge_attr: None
Z_ONE_HOT_DIM: 5
LABEL_INDEX: 7
EDGE_ATTR_DIM: 4
data_dir: "./data/qm9"
model_dir: "./trained/qm9"
log_dir: "./logs"
optimizer:
  name: Adam
  kwargs:
    betas: [0.9, 0.999]
    eps: 1e-8
criterion:
  name: MSELoss
scheduler:
  name: ReduceLROnPlateau
  kwargs:
    mode: 'min'
    factor: 0.1
    patience: 5
    verbose: True
device: cuda
